### ISSUE TITLE
이슈와 PR 템플릿을 생성합니다.

### ISSUE THREAD

**Issue by fsm12** [HARl803/auth-service#1]
## Description
- Issue와 Pull request 창을 열 때 바로 템플릿이 반영되어 있도록 설정합니다.

## Todo
- [x] 이슈 템플릿 생성하기
- [x] 이슈템플릿이 제대로 반영되었는지 확인하기
- [x] PR 템플릿 생성하기
- [x] PR 템플릿이 제대로 반영되었는지 확인하기

## Etc
- 컨벤션 지키기
